### ISSUE TITLE
Store sectors as separate lists of players, instead of having one PLAYER_LIST of all players. Same for other objects.

### ISSUE THREAD

**Issue by 2swap** [TornDotSpace/Torn-Issues#1]

**Comment by chrisj1** [comment]
What would be the advantage of this?

**Comment by DamienVesper** [comment]
Less lag as servers don't have to run through as many player instances?

**Comment by DamienVesper** [comment]
For example:
Server runs through the entire player list once and sorts them into lists by sector.
When calling upon a player, call from the smaller lists (uses less memory).
When a player moves sectors (probably need to rework movement into client) send a message to server updating the player's position (which is already calculated in the client therefore using the client's resources instead of the server) therefore should use less resources overall.

**Comment by johnnyapol** [comment]
This has been addressed during the server rewrite, for the most part (see: getPlayer() and sendWeapons()). closing this out
