### ISSUE TITLE
Allow user name changes / nickname system 

### ISSUE THREAD

**Issue by johnnyapol** [TornDotSpace/Torn-Issues#29]
Users have requested the ability to change names / have a nickname on the game. 

This issue will be blocked until #15 & #16 are resolved due to the risk of people locking themselves out of accounts and also because we want to avoid making more changes to the account system while we're transitioning it. 

Personally, I'm in favor of a username and a visible display name, where the username cannot be changed but the display name can be.

**Comment by tardisfromtornspace** [comment]
I agree too. Maybe adding something like Nickname (username) in chat?

**Comment by chrisj1** [comment]
I am working on separating usernames from display names. I am working on migrating much of the player system to sqllite. I am should a working prototype done by next week.

**Comment by chrisj1** [comment]
Another issue should we enforce that display names must be unique? I think so but would like some input.

**Comment by johnnyapol** [comment]
Maybe something like a UUID so players can "verify" themselves if we allow duplicates. We could follow the minecraft model where once you change your name the new name is "yours" and the old one is freed up for someone to reclaim after a small period of time.

**Comment by chrisj1** [comment]
@johnnyapol Sounds like a good idea. Might be more of a long term goal though.

**Comment by DamienVesper** [comment]
Display names don't have to be unique (if the usernames are unique then just distinguish players by username). Similar to Discord, a player's display name (Discord user's username) doesn't have to be unique, but the username (Discord user's 4 digit discriminator) does.

As for changing usernames, that wouldn't do good on the database, you can already change your password, and having an object that can change every aspect of itself (especially when storing with SQL) is not good, and there always has to be some uneditable part that stays the same to identify which user the object belongs to, otherwise then there's no point of having a username, you wouldn't have an identity, technically.

**Comment by tardisfromtornspace** [comment]
Also, could there be an option of adding spaces in a name/nickname? It's because some innocent names can become non-family-friendly names without spaces (example: "Pen Island Trooper" become penislandtrooper which people tend to read as "Penis Land Trooper")

**Comment by johnnyapol** [comment]
We already have the technology to do this (see tags). Closing this out
