### ISSUE TITLE
Allow clickable links to be sent through the chat

### ISSUE THREAD

**Issue by chrisj1** [TornDotSpace/Torn-Issues#32]
Allow users to send links through the chat. Could use something like https://www.npmjs.com/package/linkifyjs.

**Comment by johnnyapol** [comment]
Just a little concerned about allowing a direct link opening because we don't have a ton of moderation resources. We'd probably need a way for users to report nasty / scam / malicious links and maybe we should have links redirect to a warning page first saying "This page is not affiliated with torn.space, please do not enter your account information" etc. etc. 

This may lead to a broader discussion about moderation tool development and overhauling

**Comment by chrisj1** [comment]
I agree. I was also concerned about xss. Overall the more I think about it the worst idea it seems. I am closing this issue unless anyone wants it reopened.
